### PR TITLE
Update user email for log in.

### PR DESCRIPTION
**Pull request by vhristov5555**

### CODE REVIEW

**Comment by tjvantoll** [comment]
Hey @vhristov5555, sorry again for the late reply here. I’d actually prefer if we went with something like your.email@domain.com. In the past we’ve had problems with people adding not-especially-work-safe items on the list, so we’ve tried to avoid including shared accounts that everyone can use in these tutorials. There’s a specific step earlier on that instructs users to create their own account to use throughout the rest of the tutorials.

**Comment by vhristov5555** [comment]
I know that we are trying to avoid it. But there is this feedback https://github.com/NativeScript/playground-feedback/issues/137. People are trying to use it. Some fail. Not sure how to proceed,  I have update the email to "your.email@domain.com" and register it. But we can close this issue and answer the feedback as we intent people to create their own emails. Not to use a shared one.

**Comment by tjvantoll** [comment]
Gotcha, that makes sense. In that case maybe we can make the value something even more obvious, like `THE_EMAIL_YOU_REGISTERED_IN_AN_EARLIER_STEP_GOES_HERE`.

**Comment by vhristov5555** [comment]
Sounds good. I have change it to `THE_EMAIL_YOU_REGISTERED_IN_AN_EARLIER_STEP_GOES_HERE@domain.com`. If you think that we could change it somehow we can do it.

**Comment by tjvantoll** [comment]
@vhristov5555 Looks good. Thanks for following up on this!

**Comment by vhristov5555** [comment]
So should I merge it ?

**Comment by tjvantoll** [comment]
Yep 👍

**Pull request merged**
